# **PROJETO CHUVA**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 15, 6

In [3]:
chuva = pd.read_csv('Data/E3-262_Chuva_Mensal.csv',sep=';')

In [4]:
chuva

,Ano,Janeiro,Fevereiro,Mar√ßo,Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro
0,1985,"184,9","242,9",230,59,"126,2","14,6",4,"21,8","126,1","71,1","111,3","155,2"
1,1986,"199,6",221,"218,7","106,5","113,1","3,9","30,3",---,"34,5","60,7","242,5","389,9"
2,1987,"525,8",---,"161,3","98,1","293,8","183,9","11,8","30,9","80,2","84,8","72,7","152,1"
3,1988,"268,7","224,4","189,2","175,1","224,9","58,6","1,3","0,2","28,4","173,9","100,2","289,8"
4,1989,"312,9","344,3","288,2","66,3","21,7","52,5","150,1","32,9","52,1","80,1",88,"236,7"
5,1990,"284,1","196,9","310,1","85,8","77,9","50,6","121,2","76,3","97,2","206,8","116,3","149,8"
6,1991,"330,7","340,3","522,4","200,3","43,3","96,8","28,2","37,3","101,4",168,"67,3","237,9"
7,1992,"129,2","258,5",---,"87,2","93,5","11,6","40,9","24,7","150,6","219,6",---,"211,7"
8,1993,"221,5","225,7",110,"84,6","133,9","74,7","11,2","40,8","210,1","134,1","125,5","170,5"
9,1994,"196,9","184,4","231,6","111,4","54,9","30,5","39,2","2,4","1,8","147,6","86,6","276,3"
10,1995,"373,8","383,1","267,7","73,9","79,7","31,2","46,8","1,5","44,2","202,6","115,1",---
11,1996,"334,3","376,5","284,5","42,3","21,7","45,1","12,2","41,2","179,4","179,8","87,4","243,9"
12,1997,235,"187,6","57,1","63,2","88,2","124,7","12,5","28,8",118,"151,8","236,3","217,4"
13,1998,"231,6","430,1","211,2","56,9","133,8","16,6","16,6","45,5","99,5","203,1","41,5","198,4"
14,1999,---,339,"162,3","34,9","47,2","86,3",31,0,"76,9","64,5",76,"100,4"
15,2000,"387,7",304,"190,4",50,"9,7","9,8",74,---,"120,3","105,5",322,281
16,2001,"283,1","221,9","241,2","28,7",85,31,"31,7","26,9","82,3","213,1","181,6","292,9"
17,2002,"300,6","173,6","354,8","95,3","137,6","2,3",23,"41,5",84,"143,9","201,4","263,7"
18,2003,"443,4","141,5","250,2","45,5","36,6","20,7","24,5","27,6","41,5","176,7",133,"89,9"
19,2004,"188,8","316,9","127,2","160,5","77,4","75,6","105,6","2,2","13,8","120,6","215,5",181
20,2005,"378,3","95,9","202,1","137,3","177,1","35,1","39,8","11,5","150,3","195,3","96,6","140,1"
21,2006,"230,9","223,5","407,9","65,4","23,7","34,8","78,6","9,2","86,2","71,9",175,"353,3"
22,2007,"208,7",301,"240,2","67,6","63,1","17,2","134,3","0,1","27,4","167,2","211,7","268,7"
23,2008,388,"136,4","332,8","123,6","80,9","55,7",0,"52,5","49,9","144,3","125,4","152,9"
24,2009,"356,4",145,"73,6","75,3","58,1","28,3","157,7",---,"198,9","157,4","237,2","294,5"
25,2010,"549,1","175,4","258,9","116,4","52,8","20,2","78,4","1,2","100,4","73,8","129,2","234,7"
26,2011,"428,4","349,5","265,1",142,"40,1","81,3","1,5","49,7","10,7","218,2","73,4","393,7"
27,2012,"401,5",226,"165,9","149,1","82,4",---,"105,5","3,7","31,9","93,9",154,"623,2"
28,2013,"321,7","372,1",175,"103,4","39,4","210,9","168,8","15,3","45,1","110,7","76,6","139,9"
29,2014,"189,7","236,1","222,9","110,2",71,"11,5","51,9","20,5","82,1","23,8","209,3",258
30,2015,"249,3","303,5","265,9","100,4","87,2","25,4","62,7","40,5","280,9",---,---,"221,9"
31,2016,"242,8","225,2","288,1","92,2","141,4","207,3",0,"82,2","29,1","116,9","181,2","129,2"
32,2017,---,---,"120,8","156,3","166,1","101,6","0,2","53,4",12,"121,2","174,4","169,6"
33,2018,"238,2","84,5",---,"66,4","25,8",15,"20,5",---,"72,9","203,4","134,1",258
34,2019,---,"315,5","318,5","172,3","97,3",59,"195,1","6,7","73,7","75,9","170,8",249
35,2020,"408,1",---,"95,5","5,6","13,7","163,8",---,"62,1","22,9","213,9","162,1",---
36,2021,"373,3","174,1","137,8","55,7",---,---,---,---,---,---,---,---
37,M√©dia:,"305,79","249,3","227,97","93,64","86,67","59,66","54,6","27,85","83,8","139,89","145,04","236,04"

## **Cria√ß√£o da S√©rie**

In [5]:
chuva2 = chuva.drop(columns='Ano')
chuva2.head()

,Janeiro,Fevereiro,Mar√ßo,Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro
0,"184,9","242,9",230,59,"126,2","14,6",4,"21,8","126,1","71,1","111,3","155,2"
1,"199,6",221,"218,7","106,5","113,1","3,9","30,3",---,"34,5","60,7","242,5","389,9"
2,"525,8",---,"161,3","98,1","293,8","183,9","11,8","30,9","80,2","84,8","72,7","152,1"
3,"268,7","224,4","189,2","175,1","224,9","58,6","1,3","0,2","28,4","173,9","100,2","289,8"
4,"312,9","344,3","288,2","66,3","21,7","52,5","150,1","32,9","52,1","80,1",88,"236,7"

In [6]:
# Transformar em Array???
chuva3 = chuva2.values
chuva3

array([['184,9', '242,9', '230', '59', '126,2', '14,6', '4', '21,8',
        '126,1', '71,1', '111,3', '155,2'],
       ['199,6', '221', '218,7', '106,5', '113,1', '3,9', '30,3', '---',
        '34,5', '60,7', '242,5', '389,9'],
       ['525,8', '---', '161,3', '98,1', '293,8', '183,9', '11,8',
        '30,9', '80,2', '84,8', '72,7', '152,1'],
       ['268,7', '224,4', '189,2', '175,1', '224,9', '58,6', '1,3',
        '0,2', '28,4', '173,9', '100,2', '289,8'],
       ['312,9', '344,3', '288,2', '66,3', '21,7', '52,5', '150,1',
        '32,9', '52,1', '80,1', '88', '236,7'],
       ['284,1', '196,9', '310,1', '85,8', '77,9', '50,6', '121,2',
        '76,3', '97,2', '206,8', '116,3', '149,8'],
       ['330,7', '340,3', '522,4', '200,3', '43,3', '96,8', '28,2',
        '37,3', '101,4', '168', '67,3', '237,9'],
       ['129,2', '258,5', '---', '87,2', '93,5', '11,6', '40,9', '24,7',
        '150,6', '219,6', '---', '211,7'],
       ['221,5', '225,7', '110', '84,6', '133,9', '74,7', '11,2', '40,8',
        '210,1', '134,1', '125,5', '170,5'],
       ['196,9', '184,4', '231,6', '111,4', '54,9', '30,5', '39,2',
        '2,4', '1,8', '147,6', '86,6', '276,3'],
       ['373,8', '383,1', '267,7', '73,9', '79,7', '31,2', '46,8', '1,5',
        '44,2', '202,6', '115,1', '---'],
       ['334,3', '376,5', '284,5', '42,3', '21,7', '45,1', '12,2',
        '41,2', '179,4', '179,8', '87,4', '243,9'],
       ['235', '187,6', '57,1', '63,2', '88,2', '124,7', '12,5', '28,8',
        '118', '151,8', '236,3', '217,4'],
       ['231,6', '430,1', '211,2', '56,9', '133,8', '16,6', '16,6',
        '45,5', '99,5', '203,1', '41,5', '198,4'],
       ['---', '339', '162,3', '34,9', '47,2', '86,3', '31', '0', '76,9',
        '64,5', '76', '100,4'],
       ['387,7', '304', '190,4', '50', '9,7', '9,8', '74', '---',
        '120,3', '105,5', '322', '281'],
       ['283,1', '221,9', '241,2', '28,7', '85', '31', '31,7', '26,9',
        '82,3', '213,1', '181,6', '292,9'],
       ['300,6', '173,6', '354,8', '95,3', '137,6', '2,3', '23', '41,5',
        '84', '143,9', '201,4', '263,7'],
       ['443,4', '141,5', '250,2', '45,5', '36,6', '20,7', '24,5',
        '27,6', '41,5', '176,7', '133', '89,9'],
       ['188,8', '316,9', '127,2', '160,5', '77,4', '75,6', '105,6',
        '2,2', '13,8', '120,6', '215,5', '181'],
       ['378,3', '95,9', '202,1', '137,3', '177,1', '35,1', '39,8',
        '11,5', '150,3', '195,3', '96,6', '140,1'],
       ['230,9', '223,5', '407,9', '65,4', '23,7', '34,8', '78,6', '9,2',
        '86,2', '71,9', '175', '353,3'],
       ['208,7', '301', '240,2', '67,6', '63,1', '17,2', '134,3', '0,1',
        '27,4', '167,2', '211,7', '268,7'],
       ['388', '136,4', '332,8', '123,6', '80,9', '55,7', '0', '52,5',
        '49,9', '144,3', '125,4', '152,9'],
       ['356,4', '145', '73,6', '75,3', '58,1', '28,3', '157,7', '---',
        '198,9', '157,4', '237,2', '294,5'],
       ['549,1', '175,4', '258,9', '116,4', '52,8', '20,2', '78,4',
        '1,2', '100,4', '73,8', '129,2', '234,7'],
       ['428,4', '349,5', '265,1', '142', '40,1', '81,3', '1,5', '49,7',
        '10,7', '218,2', '73,4', '393,7'],
       ['401,5', '226', '165,9', '149,1', '82,4', '---', '105,5', '3,7',
        '31,9', '93,9', '154', '623,2'],
       ['321,7', '372,1', '175', '103,4', '39,4', '210,9', '168,8',
        '15,3', '45,1', '110,7', '76,6', '139,9'],
       ['189,7', '236,1', '222,9', '110,2', '71', '11,5', '51,9', '20,5',
        '82,1', '23,8', '209,3', '258'],
       ['249,3', '303,5', '265,9', '100,4', '87,2', '25,4', '62,7',
        '40,5', '280,9', '---', '---', '221,9'],
       ['242,8', '225,2', '288,1', '92,2', '141,4', '207,3', '0', '82,2',
        '29,1', '116,9', '181,2', '129,2'],
       ['---', '---', '120,8', '156,3', '166,1', '101,6', '0,2', '53,4',
        '12', '121,2', '174,4', '169,6'],
       ['238,2', '84,5', '---', '66,4', '25,8', '15', '20,5', '---',
        '72,9', '203,4', '134,1', '258'],
       ['---', '315,5', '318,5', '172,3', '97,3', '59', '195,1', '6,7',
        '73,7', '75,9', '170,8', '249'],
       ['408,1', '---', '95,5', '5,6', '13,7', '163,8', '---', '62,1',
        '22,9', '213,9', '162,1', '---'],
       ['373,3', '174,1', '137,8', '55,7', '---', '---', '---', '---',
        '---', '---', '---', '---'],
       ['305,79', '249,3', '227,97', '93,64', '86,67', '59,66', '54,6',
        '27,85', '83,8', '139,89', '145,04', '236,04']], dtype=object)

In [7]:
# Transformar em lista
chuva4 = list(chuva3.flatten())
print(chuva4)

['184,9', '242,9', '230', '59', '126,2', '14,6', '4', '21,8', '126,1', '71,1', '111,3', '155,2', '199,6', '221', '218,7', '106,5', '113,1', '3,9', '30,3', '---', '34,5', '60,7', '242,5', '389,9', '525,8', '---', '161,3', '98,1', '293,8', '183,9', '11,8', '30,9', '80,2', '84,8', '72,7', '152,1', '268,7', '224,4', '189,2', '175,1', '224,9', '58,6', '1,3', '0,2', '28,4', '173,9', '100,2', '289,8', '312,9', '344,3', '288,2', '66,3', '21,7', '52,5', '150,1', '32,9', '52,1', '80,1', '88', '236,7', '284,1', '196,9', '310,1', '85,8', '77,9', '50,6', '121,2', '76,3', '97,2', '206,8', '116,3', '149,8', '330,7', '340,3', '522,4', '200,3', '43,3', '96,8', '28,2', '37,3', '101,4', '168', '67,3', '237,9', '129,2', '258,5', '---', '87,2', '93,5', '11,6', '40,9', '24,7', '150,6', '219,6', '---', '211,7', '221,5', '225,7', '110', '84,6', '133,9', '74,7', '11,2', '40,8', '210,1', '134,1', '125,5', '170,5', '196,9', '184,4', '231,6', '111,4', '54,9', '30,5', '39,2', '2,4', '1,8', '147,6', '86,6', '276,3', '373,8', '383,1', '267,7', '73,9', '79,7', '31,2', '46,8', '1,5', '44,2', '202,6', '115,1', '---', '334,3', '376,5', '284,5', '42,3', '21,7', '45,1', '12,2', '41,2', '179,4', '179,8', '87,4', '243,9', '235', '187,6', '57,1', '63,2', '88,2', '124,7', '12,5', '28,8', '118', '151,8', '236,3', '217,4', '231,6', '430,1', '211,2', '56,9', '133,8', '16,6', '16,6', '45,5', '99,5', '203,1', '41,5', '198,4', '---', '339', '162,3', '34,9', '47,2', '86,3', '31', '0', '76,9', '64,5', '76', '100,4', '387,7', '304', '190,4', '50', '9,7', '9,8', '74', '---', '120,3', '105,5', '322', '281', '283,1', '221,9', '241,2', '28,7', '85', '31', '31,7', '26,9', '82,3', '213,1', '181,6', '292,9', '300,6', '173,6', '354,8', '95,3', '137,6', '2,3', '23', '41,5', '84', '143,9', '201,4', '263,7', '443,4', '141,5', '250,2', '45,5', '36,6', '20,7', '24,5', '27,6', '41,5', '176,7', '133', '89,9', '188,8', '316,9', '127,2', '160,5', '77,4', '75,6', '105,6', '2,2', '13,8', '120,6', '215,5', '181', '378,3', '95,9', '202,1', '137,3', '177,1', '35,1', '39,8', '11,5', '150,3', '195,3', '96,6', '140,1', '230,9', '223,5', '407,9', '65,4', '23,7', '34,8', '78,6', '9,2', '86,2', '71,9', '175', '353,3', '208,7', '301', '240,2', '67,6', '63,1', '17,2', '134,3', '0,1', '27,4', '167,2', '211,7', '268,7', '388', '136,4', '332,8', '123,6', '80,9', '55,7', '0', '52,5', '49,9', '144,3', '125,4', '152,9', '356,4', '145', '73,6', '75,3', '58,1', '28,3', '157,7', '---', '198,9', '157,4', '237,2', '294,5', '549,1', '175,4', '258,9', '116,4', '52,8', '20,2', '78,4', '1,2', '100,4', '73,8', '129,2', '234,7', '428,4', '349,5', '265,1', '142', '40,1', '81,3', '1,5', '49,7', '10,7', '218,2', '73,4', '393,7', '401,5', '226', '165,9', '149,1', '82,4', '---', '105,5', '3,7', '31,9', '93,9', '154', '623,2', '321,7', '372,1', '175', '103,4', '39,4', '210,9', '168,8', '15,3', '45,1', '110,7', '76,6', '139,9', '189,7', '236,1', '222,9', '110,2', '71', '11,5', '51,9', '20,5', '82,1', '23,8', '209,3', '258', '249,3', '303,5', '265,9', '100,4', '87,2', '25,4', '62,7', '40,5', '280,9', '---', '---', '221,9', '242,8', '225,2', '288,1', '92,2', '141,4', '207,3', '0', '82,2', '29,1', '116,9', '181,2', '129,2', '---', '---', '120,8', '156,3', '166,1', '101,6', '0,2', '53,4', '12', '121,2', '174,4', '169,6', '238,2', '84,5', '---', '66,4', '25,8', '15', '20,5', '---', '72,9', '203,4', '134,1', '258', '---', '315,5', '318,5', '172,3', '97,3', '59', '195,1', '6,7', '73,7', '75,9', '170,8', '249', '408,1', '---', '95,5', '5,6', '13,7', '163,8', '---', '62,1', '22,9', '213,9', '162,1', '---', '373,3', '174,1', '137,8', '55,7', '---', '---', '---', '---', '---', '---', '---', '---', '305,79', '249,3', '227,97', '93,64', '86,67', '59,66', '54,6', '27,85', '83,8', '139,89', '145,04', '236,04']

In [8]:
indice = pd.date_range('1985', periods = len(chuva4), freq = 'M')
indice

DatetimeIndex(['1985-01-31', '1985-02-28', '1985-03-31', '1985-04-30',
               '1985-05-31', '1985-06-30', '1985-07-31', '1985-08-31',
               '1985-09-30', '1985-10-31',
               ...
               '2022-03-31', '2022-04-30', '2022-05-31', '2022-06-30',
               '2022-07-31', '2022-08-31', '2022-09-30', '2022-10-31',
               '2022-11-30', '2022-12-31'],
              dtype='datetime64[ns]', length=456, freq='M')

In [9]:
serie = pd.Series(chuva4, index = indice)
serie

1985-01-31     184,9
1985-02-28     242,9
1985-03-31       230
1985-04-30        59
1985-05-31     126,2
               ...
2022-08-31     27,85
2022-09-30      83,8
2022-10-31    139,89
2022-11-30    145,04
2022-12-31    236,04
Freq: M, Length: 456, dtype: object

In [10]:
serie.plot()
plt.show()

TypeError: no numeric data to plot

## **An√°lise e Prepara√ß√£o da S√©rie**

### **M√©dia M√≥vel**

In [ ]:
media_movel = serie.rolling(window=6)
media_movel = media_movel.mean()

In [ ]:
plt.plot(media_movel);

In [ ]:
plt.plot(serie, label='S√©rie Real')
plt.plot(media_movel,color='red', label='M√©dia M√≥vel 6 meses')
plt.legend(loc='best')
plt.show()

**Decomposi√ß√£o**

In [ ]:
from statsmodels.tsa.seasonal import seasonal_decompose

In [ ]:
decomposicao = seasonal_decompose(serie)

In [ ]:
decomposicao.plot()

### **Normalidade e Transforma√ß√£o**

In [ ]:
import scipy.stats as stats

In [ ]:
stats.probplot(serie, dist="norm", plot=plt)
plt.title("Normal QQ plot")
plt.show()

**Teste Shapiro-Wilk**

CRIT√âRIOS:

N√çVEL DE SIGNIFIC√ÇNCIA DE 0,05 ou 5% (MAIS UTILIZADO)

Ho = distribui√ß√£o normal p > 0,05

Ha = distribui√ß√£o n√£o normal p <= 0,05

In [ ]:
e, p = stats.shapiro(serie)
print('Estat√≠stica de teste: {}'.format(e))
print('p-valor: {}'.format(p))

In [ ]:
# Transforma√ß√£o por log (Diminuir vari√¢ncia e melhorar normalidade)
serie2 = np.log(serie)
serie2

In [ ]:
e, p = stats.shapiro(serie2)
print('Estat√≠stica de teste: {}'.format(e))
print('p-valor: {}'.format(p))

In [ ]:
# Transforma√ß√£o por raiz c√∫bica (quando possui dados com valor zero ou negativos)
serie3 = (serie)**(1/3)
serie3

In [ ]:
stats.probplot(serie3, dist="norm", plot=plt)
plt.title("Normal QQ plot")
plt.show()

In [ ]:
e, p =stats.shapiro(serie3)
print('Estat√≠stica de teste: {}'.format(e))
print('p-valor: {}'.format(p))

In [ ]:
import seaborn as sns
sns.distplot(serie);

In [ ]:
sns.distplot(serie3);

In [ ]:
# Posso tentar mais vezes???? N√£o √© recomendado, pois n√£o adianta.
serie4 = (serie3)**(1/3)
serie4

### **Estacionaridade**

In [ ]:
import statsmodels.tsa.stattools

Teste KPSS (Kwiatkowski-Phillips-Schmidt-Shin)

Ho = n√£o √© estacion√°rio: estat√≠stica do teste > valor cr√≠tico

Ha = √© estacion√°rio:  estat√≠stica do teste < valor cr√≠tico

In [ ]:
kpss = statsmodels.tsa.stattools.kpss(serie3)
print('Estat√≠tica do teste: {:.4f}'.format(kpss[0]))
print('p_valor: {:.4f}'.format(kpss[1]))
print('Valores Cr√≠ticos:')
for chave, valor in kpss[3].items():
   print('{}: {:.4f}'.format(chave, valor))

In [ ]:
# Caso n√£o fosse estacion√°ria poderia tentar fazer a diferencia√ß√£o:
# serie5 = np.diff(serie3)

### **Autocorrela√ß√£o**

In [ ]:
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

In [ ]:
plot_acf(serie3, lags=20)
plt.show()

In [ ]:
plot_pacf(serie, lags=20)
plt.show()

A s√©rie √© autocorrelacionada, mas n√£o tem problema, pois esse √© um pressuposto da an√°lise dos res√≠duos dos modelos de s√©ries temporais.

## **Modelo AR**

Modelo arima:(p,d,q)

Modelo ar: (p,0,0)

In [ ]:
from statsmodels.tsa.arima_model import ARIMA

In [ ]:
modelo_ar = ARIMA(serie3, order = (9,0,0))

In [ ]:
resultado = modelo_ar.fit()
print(resultado.summary())

In [ ]:
plot_acf(serie3, lags=20)
plt.show()

Melhor AIC: 1337.922 = (9,0,0)

### **An√°lise dos Res√≠duos**

In [ ]:
residuos = resultado.resid

In [ ]:
residuos.plot()
plt.show()

**Normalidade**

In [ ]:
stats.probplot(residuos, dist="norm", plot=plt)
plt.title("Normal QQ plot")
plt.show()

In [ ]:
e, p = stats.shapiro(residuos)
print('Estat√≠stica de teste: {}'.format(e))
print('p-valor: {}'.format(p))

In [ ]:
import seaborn as sns
sns.distplot(residuos);

**Autocorrela√ß√£o**

In [ ]:
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

In [ ]:
plot_acf(residuos, lags=20)
plt.show()

In [ ]:
plot_pacf(residuos, lags=20)
plt.show()

In [ ]:
plt.plot(serie3, label='S√©rie Real')
plt.plot(serie3-residuos,color='red', label='Res√≠duos')
plt.legend(loc='best')
plt.show()

**Previs√£o**

In [ ]:
resultado.fittedvalues

In [ ]:
previsao = resultado.predict(431, end=443)
previsao

In [ ]:
previsao2 = resultado.forecast(12)
previsao2

In [ ]:
previsao2[0]

In [ ]:
plt.plot(serie3,color='yellow', label='S√©rie Real')
plt.plot(previsao,color='blue', label='Previs√£o')
plt.plot(serie3-residuos,color='red', label='Res√≠duos')
plt.legend(loc='best')
plt.show()

In [ ]:
prev_escala = pd.DataFrame(previsao ** 3, columns=['Previs√£o_AR'])
prev_escala

In [ ]:
pd.concat([serie,prev_escala]).plot();

## **Modelo MA**

Modelo arima:(p,d,q)

Modelo ma: (0,0,q)

In [ ]:
from statsmodels.tsa.arima_model import ARIMA

In [ ]:
modelo_ma = ARIMA(serie3, order = (0,0,8))

In [ ]:
resultado_ma = modelo_ma.fit()
print(resultado_ma.summary())

Modelo AR: AIC = 1337.922 (9,0,0)

Modelo MA: AIC = 1411.696 (0,0,8)

### **An√°lise dos Res√≠duos**

In [ ]:
residuos_ma = resultado_ma.resid

In [ ]:
residuos_ma.plot()
plt.show()

**Normalidade**

In [ ]:
stats.probplot(residuos_ma, dist="norm", plot=plt)
plt.title("Normal QQ plot")
plt.show()

In [ ]:
e, p = stats.shapiro(residuos_ma)
print('Estat√≠stica de teste: {}'.format(e))
print('p-valor: {}'.format(p))

In [ ]:
import seaborn as sns
sns.distplot(residuos_ma);

**Autocorrela√ß√£o**

In [ ]:
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

In [ ]:
plot_acf(residuos_ma, lags=30)
plt.show()

In [ ]:
plot_pacf(residuos_ma, lags=30)
plt.show()

In [ ]:
plt.plot(serie3, label='S√©rie Real')
plt.plot(serie3-residuos_ma,color='red', label='Res√≠duos')
plt.legend(loc='best')
plt.show()

**Previs√£o**

In [ ]:
resultado_ma.fittedvalues

In [ ]:
previsao_ma = resultado_ma.predict(start=431, end=443)
previsao_ma

In [ ]:
plt.plot(serie3,color='yellow', label='S√©rie Real')
plt.plot(previsao_ma,color='blue', label='Previs√£o')
plt.plot(serie3-residuos_ma,color='red', label='Res√≠duos')
plt.legend(loc='best')
plt.show()

In [ ]:
prev_escala_ma = pd.DataFrame(previsao_ma ** 3, columns=['Previs√£o_MA'])
prev_escala_ma

In [ ]:
pd.concat([serie,prev_escala_ma]).plot();

## **Modelo ARMA**

Modelo arima:(p,d,q)

Modelo arma: (p,0,q)

Modelo AR: AIC = 1337.922 (9,0,0)

Modelo MA: AIC = 1411.696 (0,0,8)

In [ ]:
from statsmodels.tsa.arima_model import ARIMA

In [ ]:
modelo_arma = ARIMA(serie3, order = (10,0,2))

In [ ]:
resultado_arma = modelo_arma.fit()
print(resultado_arma.summary())

Modelo AR: AIC = 1337.922 (9,0,0)

Modelo MA: AIC = 1411.696 (0,0,8)

Modelo ARMA: Melhor AIC = 1273.766 (10,0,2)

### **An√°lise dos Res√≠duos**

In [ ]:
residuos_arma = resultado_arma.resid

In [ ]:
residuos_arma.plot()
plt.show()

**Normalidade**

In [ ]:
stats.probplot(residuos_arma, dist="norm", plot=plt)
plt.title("Normal QQ plot")
plt.show()

In [ ]:
e, p = stats.shapiro(residuos_arma)
print('Estat√≠stica de teste: {}'.format(e))
print('p-valor: {}'.format(p))

In [ ]:
import seaborn as sns
sns.distplot(residuos_arma);

**Autocorrela√ß√£o**

In [ ]:
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

In [ ]:
plot_acf(residuos_arma, lags=30)
plt.show()

In [ ]:
plot_pacf(residuos_arma, lags=30)
plt.show()

In [ ]:
plt.plot(serie3, label='S√©rie Real')
plt.plot(serie3-residuos_arma,color='red', label='Res√≠duos')
plt.legend(loc='best')
plt.show()

**Previs√£o**

In [ ]:
resultado_arma.fittedvalues

In [ ]:
previsao_arma = resultado_arma.predict(start=431, end=455)
previsao_arma

In [ ]:
plt.plot(serie3,color='yellow', label='S√©rie Real')
plt.plot(previsao_arma,color='blue', label='Previs√£o')
plt.plot(serie3-residuos_arma,color='red', label='Res√≠duos')
plt.legend(loc='best')
plt.show()

In [ ]:
prev_escala_arma = pd.DataFrame(previsao_arma ** 3, columns=['Previs√£o_ARMA'])
prev_escala_arma

In [ ]:
pd.concat([serie,prev_escala_arma]).plot();

## **Modelo ARIMA**

Modelo arima:(p,d,q)

Modelo AR: AIC = 1337.922 (9,0,0)

Modelo MA: Melhor AIC = 1411.696 (0,0,8)

Modelo ARMA: Melhor AIC = 1273.766 (10,0,2)

In [ ]:
from statsmodels.tsa.arima_model import ARIMA

In [ ]:
modelo_arima = ARIMA(serie3, order = (10,1,2))

In [ ]:
resultado_arima = modelo_arima.fit()
print(resultado_arima.summary())

Modelo AR: Melhor AIC = 1339.919 (10,0,0)

Modelo MA: Melhor AIC = 1411.696 (0,0,8)

Modelo ARMA: Melhor AIC = 1273.766 (10,0,2)

Modelo ARIMA: Melhor AIC = 1319.230 (10,1,2)

### **An√°lise dos Res√≠duos**

In [ ]:
residuos_arima = resultado_arima.resid

In [ ]:
residuos_arima.plot()
plt.show()

**Normalidade**

In [ ]:
stats.probplot(residuos_arima, dist="norm", plot=plt)
plt.title("Normal QQ plot")
plt.show()

In [ ]:
e, p = stats.shapiro(residuos_arima)
print('Estat√≠stica de teste: {}'.format(e))
print('p-valor: {}'.format(p))

In [ ]:
import seaborn as sns
sns.distplot(residuos_arima);

**Autocorrela√ß√£o**

In [ ]:
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

In [ ]:
plot_acf(residuos_arima, lags=30)
plt.show()

In [ ]:
plot_pacf(residuos_arima, lags=30)
plt.show()

In [ ]:
plt.plot(serie3, label='S√©rie Real')
plt.plot(serie3-residuos_arima,color='red', label='Res√≠duos')
plt.legend(loc='best')
plt.show()

**Previs√£o**

In [ ]:
resultado_arima.fittedvalues

In [ ]:
previsao_arima = resultado_arima.predict(start=430, end=443)
previsao_arima

In [ ]:
previsao_arima2 = resultado_arima.forecast(24)
previsao_arima2[0]

In [ ]:
prev_escala_arima = pd.DataFrame(previsao_arima2[0] ** 3, columns=['Previs√£o_ARIMA'])
prev_escala_arima

In [ ]:
pd.concat([serie,prev_escala_arima]).plot();

## **Modelo AUTO ARIMA**

Modelo arima:(p,d,q)

Modelo SARIMA: (p,d,q)(P,D,Q)

Modelo AR: Melhor AIC = 1337.922 = (9,0,0)

Modelo MA: Melhor AIC = 1411.696 (0,0,8)

Modelo ARMA: Melhor AIC = 1273.766 (10,0,2)

Modelo ARIMA: Melhor AIC = 1319.230 (10,1,2)

In [ ]:
pip install pmdarima

In [ ]:
from pmdarima.arima import auto_arima

In [ ]:
### AUTOARIMA
modelo_auto = auto_arima(serie3, trace = True, stepwise = False, seasonal=True, max_p=10, max_q=10,
                          max_P=4, max_Q=4, start_p=0, start_q=0, start_P=0, start_Q=0, m=12)

# Trace: apresenta no console a lista dos modelos.
# stepwise: sele√ß√£o gradual(processo mais r√°pido, por√©m menos minucioso).
# m: per√≠odo sazonal (neste caso mensal).
# Interessante dobrar as ordens m√°ximas: max.p = 10, max.q = 10, max.P = 4, max.Q = 4

In [ ]:
print(modelo_auto.aic())

Modelo AR: Melhor AIC = 1339.919 (10,0,0)

Modelo MA: Melhor AIC = 1411.696 (0,0,8)

Modelo ARMA: Melhor AIC = 1273.766 (10,0,2)

Modelo ARIMA: Melhor AIC = 1319.230 (10,1,2)

Modelo_AUTOARIMA: AIC=1270.5894 ARIMA(0,0,0)(1,0,3)

In [ ]:
resultado_auto = modelo_auto.fit(serie3)
print(resultado_auto.summary())

### **An√°lise dos Res√≠duos**

In [ ]:
residuos_auto = resultado_auto.resid
residuos_auto()

In [ ]:
plt.plot(residuos_auto())
plt.show()

**Normalidade**

In [ ]:
stats.probplot(residuos_auto(), dist="norm", plot=plt)
plt.title("Normal QQ plot")
plt.show()

In [ ]:
e, p = stats.shapiro(residuos_auto())
print('Estat√≠stica de teste: {}'.format(e))
print('p-valor: {}'.format(p))

In [ ]:
import seaborn as sns
sns.distplot(residuos_auto());

**Autocorrela√ß√£o**

In [ ]:
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

In [ ]:
plot_acf(residuos_auto(), lags=30)
plt.show()

In [ ]:
plot_pacf(residuos_auto(), lags=30)
plt.show()

In [ ]:
plt.plot(serie3, label='S√©rie Real')
plt.plot(serie3-residuos_auto(),color='red', label='Res√≠duos')
plt.legend(loc='best')
plt.show()

**Previs√£o**

In [ ]:
previsao_auto = resultado_auto.predict(n_periods=48)
previsao_auto

In [ ]:
prev_escala_auto = pd.DataFrame(previsao_auto ** 3, columns=['Previs√£o_SARIMA'])
prev_escala_auto

In [ ]:
pd.concat([serie,prev_escala_auto]).plot();

## **An√°lise final do projeto**

**COMPARA√á√ÉO DOS MODELOS**

Modelo AR: Melhor AIC = 1339.919 (10,0,0)

Modelo MA: Melhor AIC = 1411.696 (0,0,8)

Modelo ARMA: Melhor AIC = 1273.766 (10,0,2)

Modelo ARIMA: Melhor AIC = 1319.230 (10,1,2)

**Modelo_SARIMA (AutoArima): AIC=1270.5894 ARIMA(0,0,0)(1,0,3)**

**DESEMPENHO DOS MODELOS**

In [ ]:
# Lista com valores reais de 2021
lista = [373.3, 174.1, 137.8, 55.7]
valores_reais = pd.DataFrame(lista, columns = ['valores reais'])
print(valores_reais)

In [ ]:
auto = prev_escala_auto.iloc[0:4]
auto

In [ ]:
desempenho = pd.concat([valores_reais, auto],axis=1)
desempenho

In [ ]:
ar = prev_escala.iloc[1:5]
ar

In [ ]:
pd.DataFrame.reset_index(ar, drop=True, inplace=True)
ar

In [ ]:
ma = prev_escala_ma.iloc[1:5]
ma

In [ ]:
pd.DataFrame.reset_index(ma, drop=True, inplace=True)
ma

In [ ]:
arma = prev_escala_arma.iloc[1:5]
arma

In [ ]:
pd.DataFrame.reset_index(arma, drop=True, inplace=True)
arma

In [ ]:
arima = prev_escala_arima.iloc[0:4]
arima

In [ ]:
desempenho = pd.concat([desempenho, ar, ma, arma, arima],axis=1)
desempenho

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

**ERRO M√âDIO ABSOLUTO (MAE)**

In [ ]:
print('ERRO M√âDIO ABSOLUTO (MAE)')
mae_sarima = mean_absolute_error(desempenho['valores reais'], desempenho['Previs√£o_SARIMA'])
print('SARIMA: {:.2f}'.format(mae_sarima))
mae_ar = mean_absolute_error(desempenho['valores reais'], desempenho['Previs√£o_AR'])
print('AR: {:.2f}'.format(mae_ar))
mae_ma = mean_absolute_error(desempenho['valores reais'], desempenho['Previs√£o_MA'])
print('MA: {:.2f}'.format(mae_ma))
mae_arma = mean_absolute_error(desempenho['valores reais'], desempenho['Previs√£o_ARMA'])
print('ARMA: {:.2f}'.format(mae_arma))
mae_arima = mean_absolute_error(desempenho['valores reais'], desempenho['Previs√£o_ARIMA'])
print('ARIMA: {:.2f}'.format(mae_arima))

**ERRO QUADR√ÅTICO M√âDIO (MSE)**

In [ ]:
print('ERRO QUADR√ÅTICO M√âDIO (MSE)')
mse_sarima = mean_squared_error(desempenho['valores reais'], desempenho['Previs√£o_SARIMA'])
print('SARIMA: {:.2f}'.format(mse_sarima))
mse_ar = mean_squared_error(desempenho['valores reais'], desempenho['Previs√£o_AR'])
print('AR: {:.2f}'.format(mse_ar))
mse_ma = mean_squared_error(desempenho['valores reais'], desempenho['Previs√£o_MA'])
print('MA: {:.2f}'.format(mse_ma))
mse_arma = mean_squared_error(desempenho['valores reais'], desempenho['Previs√£o_ARMA'])
print('ARMA: {:.2f}'.format(mse_arma))
mse_arima = mean_squared_error(desempenho['valores reais'], desempenho['Previs√£o_ARIMA'])
print('ARIMA: {:.2f}'.format(mse_arima))

**RAIZ DO ERRO QUADR√ÅTICO M√âDIO (RMSE)**

In [ ]:
print('RAIZ DO ERRO QUADR√ÅTICO M√âDIO (RMSE)')
rmse_sarima = mean_squared_error(desempenho['valores reais'], desempenho['Previs√£o_SARIMA'], squared=False)
print('SARIMA: {:.2f}'.format(rmse_sarima))
rmse_ar = mean_squared_error(desempenho['valores reais'], desempenho['Previs√£o_AR'], squared=False)
print('AR: {:.2f}'.format(rmse_ar))
rmse_ma = mean_squared_error(desempenho['valores reais'], desempenho['Previs√£o_MA'], squared=False)
print('MA: {:.2f}'.format(rmse_ma))
rmse_arma = mean_squared_error(desempenho['valores reais'], desempenho['Previs√£o_ARMA'], squared=False)
print('ARMA: {:.2f}'.format(rmse_arma))
rmse_arima = mean_squared_error(desempenho['valores reais'], desempenho['Previs√£o_ARIMA'], squared=False)
print('ARIMA: {:.2f}'.format(rmse_arima))

**Sugest√µes de Estudos:**

1) Criar uma s√©rie com a data final at√© dezembro de 2019.

2) Fazer todo o estudo com o dataset elnino do Python.

https://www.statsmodels.org/devel/datasets/index.html

In [ ]:
import statsmodels.api as sm
sm.datasets.elnino.load_pandas().data